services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
    command : ["redis-server", "--requirepass", "systempass"]
    ports:
      - 6379:6379
      - 8001:8001

